# CREATE DATABASE MOVIE_RATINGS;

-- CREATE TABLE MOVIES(
-- 	M_ID INT PRIMARY KEY,
--     M_NAME VARCHAR(50));
 
  
-- CREATE TABLE RATINGS(
-- 	M_ID INT,
-- 	P_ID INT,
-- 	RATING INT NULL,
--     FOREIGN KEY (M_ID) REFERENCES MOVIES(M_ID));

-- Movie Data

INSERT INTO MOVIES VALUES( 1 ,  "Black Panther" );
INSERT INTO MOVIES VALUES( 2 ,  "Luca" );
INSERT INTO MOVIES VALUES( 3 ,  "Black Widow" );
INSERT INTO MOVIES VALUES( 4 ,  "Respect" );
INSERT INTO MOVIES VALUES( 5 ,  "The Imitation Game" );
INSERT INTO MOVIES VALUES( 6 ,  "Hidden Figures" );

-- Rating Data

INSERT INTO RATINGS VALUES( 1 ,  1 ,  1 );
INSERT INTO RATINGS VALUES( 2 ,  1 ,  0 );
INSERT INTO RATINGS VALUES( 3 ,  1 ,  4 );
INSERT INTO RATINGS VALUES( 4 ,  1 ,  NULL );
INSERT INTO RATINGS VALUES( 5 ,  1 ,  NULL );
INSERT INTO RATINGS VALUES( 6 ,  1 ,  3 );
INSERT INTO RATINGS VALUES( 1 ,  2 ,  0 );
INSERT INTO RATINGS VALUES( 2 ,  2 ,  2 );
INSERT INTO RATINGS VALUES( 3 ,  2 ,  4 );
INSERT INTO RATINGS VALUES( 4 ,  2 ,  NULL );
INSERT INTO RATINGS VALUES( 5 ,  2 ,  1 );
INSERT INTO RATINGS VALUES( 6 ,  2 ,  1 );
INSERT INTO RATINGS VALUES( 1 ,  3 ,  0 );
INSERT INTO RATINGS VALUES( 2 ,  3 ,  5 );
INSERT INTO RATINGS VALUES( 3 ,  3 ,  4 );
INSERT INTO RATINGS VALUES( 4 ,  3 ,  3 );
INSERT INTO RATINGS VALUES( 5 ,  3 ,  3 );
INSERT INTO RATINGS VALUES( 6 ,  3 ,  1 );
INSERT INTO RATINGS VALUES( 1 ,  4 ,  0 );
INSERT INTO RATINGS VALUES( 2 ,  4 ,  0 );
INSERT INTO RATINGS VALUES( 3 ,  4 ,  2 );
INSERT INTO RATINGS VALUES( 4 ,  4 ,  0 );
INSERT INTO RATINGS VALUES( 5 ,  4 ,  5 );
INSERT INTO RATINGS VALUES( 6 ,  4 ,  5 );
INSERT INTO RATINGS VALUES( 1 ,  5 ,  3 );
INSERT INTO RATINGS VALUES( 2 ,  5 ,  4 );
INSERT INTO RATINGS VALUES( 3 ,  5 ,  0 );
INSERT INTO RATINGS VALUES( 4 ,  5 ,  0 );
INSERT INTO RATINGS VALUES( 5 ,  5 ,  0 );
INSERT INTO RATINGS VALUES( 6 ,  5 ,  2 );
INSERT INTO RATINGS VALUES( 1 ,  6 ,  NULL );
INSERT INTO RATINGS VALUES( 2 ,  6 ,  2 );
INSERT INTO RATINGS VALUES( 3 ,  6 ,  NULL );
INSERT INTO RATINGS VALUES( 4 ,  6 ,  1 );
INSERT INTO RATINGS VALUES( 5 ,  6 ,  3 );
INSERT INTO RATINGS VALUES( 6 ,  6 ,  NULL );
INSERT INTO RATINGS VALUES( 1 ,  7 ,  NULL );
INSERT INTO RATINGS VALUES( 2 ,  7 ,  4 );
INSERT INTO RATINGS VALUES( 3 ,  7 ,  1 );
INSERT INTO RATINGS VALUES( 4 ,  7 ,  0 );
INSERT INTO RATINGS VALUES( 5 ,  7 ,  0 );
INSERT INTO RATINGS VALUES( 6 ,  7 ,  3 );
INSERT INTO RATINGS VALUES( 1 ,  8 ,  1 );
INSERT INTO RATINGS VALUES( 2 ,  8 ,  3 );
INSERT INTO RATINGS VALUES( 3 ,  8 ,  0 );
INSERT INTO RATINGS VALUES( 4 ,  8 ,  5 );
INSERT INTO RATINGS VALUES( 5 ,  8 ,  4 );
INSERT INTO RATINGS VALUES( 6 ,  8 ,  1 );
INSERT INTO RATINGS VALUES( 1 ,  9 ,  2 );
INSERT INTO RATINGS VALUES( 2 ,  9 ,  3 );
INSERT INTO RATINGS VALUES( 3 ,  9 ,  3 );
INSERT INTO RATINGS VALUES( 4 ,  9 ,  5 );
INSERT INTO RATINGS VALUES( 5 ,  9 ,  5 );
INSERT INTO RATINGS VALUES( 6 ,  9 ,  0 );
